### ISSUE TITLE
KeyError: 'entities'

### ISSUE THREAD

**Issue by eldios** [openviess/PyViCare#1]
hey @somm15,
Using [oischinger/ha_vicare](https://github.com/oischinger/ha_vicare) I got the following error:

```
homeassistant_1  | 2019-01-14 18:12:54 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform vicare
homeassistant_1  | Traceback (most recent call last):                                                                         
homeassistant_1  |   File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform             
homeassistant_1  |     SLOW_SETUP_MAX_WAIT, loop=hass.loop)                                                                     
homeassistant_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for                                  
homeassistant_1  |     return fut.result()                                                                                      
homeassistant_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                      
homeassistant_1  |     result = self.fn(*self.args, **self.kwargs)                                                              
homeassistant_1  |   File "/config/custom_components/sensor/vicare.py", line 19, in setup_platform                          
homeassistant_1  |     t = ViCareSession(config.get(CONF_USER), config.get(CONF_PASSWORD), "/tmp/vicare_token.save")          
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 56, in __init__                     
homeassistant_1  |     self._getInstallations()                                                                                                                                                                                                                                              
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 186, in _getInstallations           
homeassistant_1  |     self.href=self.installations["entities"][0]["links"][0]["href"]                                                                                                                                                                                                        homeassistant_1  | KeyError: 'entities'
```

Ignore the `homeassistant_1` log prefix, that's added by docker-compose.

Version: `Home Assistant 0.85.0`
Deployed via Docker image `homeassistant/homeassistant`

Any hint on what's happening there?

**Comment by somm15** [comment]
I suspect that you have only an installation number 2 or something like that.
Could you please add the following lines to the script calling PyViCare:

```
import logging
logger = logging.getLogger("ViCare") 
handler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s %(name)-12s %(levelname)-8s %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
```

I'll analyse the JSON

**Comment by eldios** [comment]
@somm15 it didn't change the output LOG level unfortunately

**Comment by eldios** [comment]
it's happening here, btw:

https://github.com/oischinger/ha_vicare/blob/master/vicare.py#L19

**Comment by somm15** [comment]
I forgot to mention that you have to fetch the new code from GitHub.
I know where it happens but I don't know the JSON response you get from the API unfortunately...

**Comment by eldios** [comment]
@somm15 is the new code on PIP already?

**Comment by somm15** [comment]
@eldios Now it is as version 0.0.8

**Comment by eldios** [comment]
```
homeassistant_1  | 2019-01-14 22:01:19,983 ViCare       INFO     Token serialized to /tmp/vicare_token.save                                                                                                                                                                                   
homeassistant_1  | 2019-01-14 22:01:19 INFO (SyncWorker_28) [ViCare] Token serialized to /tmp/vicare_token.save                                                                                                                                                                               
homeassistant_1  | 2019-01-14 22:01:19,983 ViCare       INFO     New token created                                                                                                                                                                                                            
homeassistant_1  | 2019-01-14 22:01:19 INFO (SyncWorker_28) [ViCare] New token created                                                                                                                                                                                                        
homeassistant_1  | 2019-01-14 22:01:20,409 ViCare       DEBUG    {'error': 'NO TOKEN AVAILABLE'}                                                                                                                                                                                              
homeassistant_1  | 2019-01-14 22:01:20 DEBUG (SyncWorker_28) [ViCare] {'error': 'NO TOKEN AVAILABLE'}                                                                                                                                                                                         
homeassistant_1  | 2019-01-14 22:01:20 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform vicare                                                                                                                                                            
homeassistant_1  | Traceback (most recent call last):                                                                                                                                                                                                                                         
homeassistant_1  |   File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform                                                                                                                                                                         
homeassistant_1  |     SLOW_SETUP_MAX_WAIT, loop=hass.loop)                                                                                                                                                                                                                                   
homeassistant_1  |   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for                                                                                                                                                                                                  
homeassistant_1  |     return fut.result()                                                                                                                                                                                                                                                    
homeassistant_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                                                                                                                                                                            
homeassistant_1  |     result = self.fn(*self.args, **self.kwargs)                                                                                                                                                                                                                            
homeassistant_1  |   File "/config/custom_components/sensor/vicare.py", line 26, in setup_platform                                                                                                                                                                                            
homeassistant_1  |     t = ViCareSession(config.get(CONF_USER), config.get(CONF_PASSWORD), "/tmp/vicare_token.save")                                                                                                                                                                          
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 50, in __init__
homeassistant_1  |     self._getInstallations()
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 182, in _getInstallations
homeassistant_1  |     self.id=self.installations["entities"][0]["properties"]["id"]
homeassistant_1  | KeyError: 'entities'
```

**Comment by somm15** [comment]
Wrong username or password.
The username is an e-mail address. 

The error handling could be improve to print a meaningful message 👍

**Comment by eldios** [comment]
I just double-checked by trying those same entries via the mobile Android App and they're correct sadly.

I have the entries wrapped in " and there's ! and ? in the password. I don't think it should be a problem, but FYI.

**Comment by somm15** [comment]
Good point, I have to URL encode the password. I'll fix that later tonight or tomorrow.
My bad.

**Comment by somm15** [comment]
0.0.9 done. I hope it solves it

**Comment by eldios** [comment]
@somm15 to be sure I removed all punctuation from my password and tried again with 0.0.9 ... same error :)

**Comment by somm15** [comment]
Did you delete /tmp/vicare_token.save  ?

**Comment by eldios** [comment]
I did and I also deleted and reinstalled the Python module :)

**Comment by somm15** [comment]
and can you login there?
https://iam.viessmann.com/idp/v1/authorize?response_type=code&client_id=79742319e39245de5f91d15ff4cac2a8&redirect_uri=vicare%3A%2F%2Foauth-callback%2Feverest&scope=openid&state=07V6NIymFCZwnWkoL8SkRZZikeFmo2

**Comment by eldios** [comment]
yup, logging in works perfectly through web :+1:

**Comment by somm15** [comment]
Ok, last attempt for today. Version 0.0.11

**Comment by somm15** [comment]
Could you also run a python script with:
```
import sys
import logging
from PyViCare import ViCareSession
t=ViCareSession("xxx@xxx","password","token.bin")
i=t.getInstallations()
```

**Comment by eldios** [comment]
```
root@2226cb6ee98c:/usr/src/app# python test.py 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    t=ViCareSession("xeldiosx@gmail.com","0viessman020190","token.bin")
  File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 51, in __init__
    self._getInstallations()
  File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 184, in _getInstallations
    self.id=self.installations["entities"][0]["properties"]["id"]
KeyError: 'entities'

root@2226cb6ee98c:/usr/src/app# cat test.py 
import sys
import logging
from PyViCare import ViCareSession
t=ViCareSession("CORRECT_USERNAME","CORRECT_PASSWORD","token.bin")
i=t.getInstallations()
```

**Comment by somm15** [comment]
@eldios I deleted your comment, password was in the logs.

**Comment by eldios** [comment]
oh... thanks :)
well you can try yourself then if you want. Let me know when you're done and I'll change it again as it was a temporary one.

**Comment by somm15** [comment]
Change it then. I tried and it does work now with version 0.0.11
There must be something with your or my install. I just can't figure out what.

**Comment by somm15** [comment]
Ok, it looks like I don't handle path properly yet.
Try storing to token.bin without a folder. I'll fix it.

**Comment by eldios** [comment]
in the test.py script I used there was no folder though.. it was just "token.bin"

I'm using the Docker image "image: homeassistant/home-assistant" and then installing the PyVicare module via pip inside the container.

it's using Python 3.6.8 as shown above... I'll try to think of anything else that could interfere :thinking:

**Comment by somm15** [comment]
Version 0.0.13 should be better. No problems with path anymore. 
But for a reason it does not refresh on Pypi

**Comment by eldios** [comment]
after installing 0.0.16 it's now giving my issues with importing ViCareSession :thinking:

**Comment by somm15** [comment]
yeah, fixed in the next one (17). I broke a few stuff trying to fix. I'll work on test next time.

**Comment by eldios** [comment]
okay so... it worked but:
* I had to remove any punctuation from the password
* it didn't want to work from the module so I have to recreate the token via CLI using the test.py and then copy it in place... then the homeassistant module worked :man_shrugging: 

let's keep working on it in the next days. Thanks for now! :+1: :tada: we're off to a good start!

**Comment by somm15** [comment]
Version 0.0.20 should be much better.
- better logging
- can handle incorrect token serialisation files
- can handle no token_file parameter

I tested it successfully with a 32 char length password full random with special chars

**Comment by eldios** [comment]
I guess it's important to say that I'm using `Home Assistant 0.85.0` :)

that said I'm now getting a different error:
```
homeassistant_1  | 2019-01-15 14:33:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.vicare_currentdesiredtemperature fails                                                                                                                                            
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
homeassistant_1  |     await self.async_device_update()
homeassistant_1  |   File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
homeassistant_1  |     await self.hass.async_add_executor_job(self.update)
homeassistant_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
homeassistant_1  |     result = self.fn(*self.args, **self.kwargs)
homeassistant_1  |   File "/config/custom_components/sensor/vicare.py", line 64, in update
homeassistant_1  |     self._state = api_method(self._api)
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 386, in getCurrentDesiredTemperature
homeassistant_1  |     return self.getProperty("heating.circuits.0.operating.programs."+self.getActiveProgram())["properties"]["temperature"]["value"]                                                                                                                                       
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 368, in getActiveProgram
homeassistant_1  |     return self.getProperty("heating.circuits.0.operating.programs.active")["properties"]["value"]["value"]
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 206, in getProperty
homeassistant_1  |     j=self.__get(url)
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 143, in __get
homeassistant_1  |     r=self.oauth.get(url).json()
homeassistant_1  | AttributeError: 'NoneType' object has no attribute 'get'
homeassistant_1  | 2019-01-15 14:33:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.vicare_domestichotwaterstoragetemperature fails                                                                                                                                   
homeassistant_1  | Traceback (most recent call last):
homeassistant_1  |   File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
homeassistant_1  |     await self.async_device_update()
homeassistant_1  |   File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
homeassistant_1  |     await self.hass.async_add_executor_job(self.update)
homeassistant_1  |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
homeassistant_1  |     result = self.fn(*self.args, **self.kwargs)
homeassistant_1  |   File "/config/custom_components/sensor/vicare.py", line 64, in update
homeassistant_1  |     self._state = api_method(self._api)
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 398, in getDomesticHotWaterStorageTemperature
homeassistant_1  |     return self.getProperty("heating.dhw.sensors.temperature.hotWaterStorage")["properties"]["value"]["value"]
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 206, in getProperty
homeassistant_1  |     j=self.__get(url)
homeassistant_1  |   File "/usr/local/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 143, in __get
homeassistant_1  |     r=self.oauth.get(url).json()
homeassistant_1  | AttributeError: 'NoneType' object has no attribute 'get'
```
For all sensors and climate components... but:
```
root@2226cb6ee98c:/usr/src/app# python test.py 
None
token renewed
```
not happening with the test :thinking:

**Comment by somm15** [comment]
I just got it working with home assistant 0.85.1 without any problem.
Can you try it not in a container? 
Make also sure to uninstall and reinstall PyViCare with pip3.

**Comment by somm15** [comment]
My config looks like this:
```
sensor:
  - platform: vicare
    user: 'somm15@gmail.com'
    password: 'complex_password'
    client_id: '79742319e39245de5f91d15ff4cac2a8'
    client_secret: '8ad97aceb92c5892e102b093c7c083fa'
```
And I put the files there:
```
(homeassistant) Securitys-MacBook-Pro-2:.homeassistant sgillet$ ls -l ~/.homeassistant/custom_components/*
-rw-r--r--  1 sgillet  staff  980 Jan 15 15:02 /Users/sgillet/.homeassistant/custom_components/README.md

/Users/sgillet/.homeassistant/custom_components/climate:
total 16
-rw-r--r--  1 sgillet  staff  4351 Jan 15 15:02 vicare.py

/Users/sgillet/.homeassistant/custom_components/sensor:
total 8
drwxr-xr-x  3 sgillet  staff    96 Jan 15 15:10 __pycache__
-rw-r--r--  1 sgillet  staff  2358 Jan 15 15:02 vicare.py

(homeassistant) Securitys-MacBook-Pro-2:.homeassistant sgillet$ pip3 show PyViCare
Name: PyViCare
Version: 0.0.20
Summary: Library to communicate with the Viessmann ViCare API
Home-page: https://github.com/somm15/PyViCare
Author: Simon Gillet
Author-email: mail+pyvicare@gillet.ninja
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires: requests-oauthlib
Required-by: 
```

**Comment by eldios** [comment]
it seems that you're also using Python 3.7 ... while the image I'm using is set on Python-3.6
Again shouldn't make any difference but who knows at this point.

Will continue testing.

0.0.20 is definitely holding better btw... I'll keep you posted with the test results :+1:

**Comment by maxmikli** [comment]
I got it up and running, but i cannot change program in home assistant.
I am using the climate script from https://github.com/oischinger/ha_vicare
sensor is up and running fine! Greets Max

2019-02-07 16:22:56 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.vicare_programs fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/vicare.py", line 83, in update
    self._state = api_method(self._api)
  File "/config/deps/lib/python3.6/site-packages/PyViCare/PyViCare.py", line 379, in getPrograms
    return self.getProperty("heating.circuits.0.operating.programs")["entities"][9]["properties"]["components"]
IndexError: list index out of range

**Comment by vandenberghev** [comment]
@maxmikli Circuit index errors should be resolved by my [latest pull request](https://github.com/somm15/PyViCare/commit/1da869463fec35321a8e437b465767457ae29c01).
However, the PyViCare PYPI package hasn't been updated yet. Once the new package is out, my changes in the ha_vicare repo can be merged. That should fix your problem.

**Comment by somm15** [comment]
I just upload PyViCare 0.0.30
It's the latest version from Git.
Let me know if everything is ok.

Sorry for the delay... family, job ... etc

**Comment by vandenberghev** [comment]
Thanks!
